### PR TITLE
Test change that shows how transfer bytes are off when any server side auth used

### PR DESCRIPTION
**Pull request by cstamas**
When server uses any kind of auth, transfered bytes reported when
using this connector are all off: they are doubled.

On related note, this also yields for support of EXPECT-CONTINUE
support, something fixed in later OkHTTP clients.

Reason seems to be that transfer listener is not notified about retries. 
Moreover, lack of expect-continue support causes that this connector
uploads whole file first time, just to get 401 response, after which it
re-uploads again the whole file, but with auth header equipped.

### CODE REVIEW

**Comment by cstamas** [comment]
This change results in these test failures:

```
[ERROR] Failures: 
[ERROR]   PutAuthSslTest>PutTest.testArtifactUpload:68 expected:<8> but was:<16>
[ERROR]   PutAuthTest>PutTest.testArtifactUpload:68 expected:<8> but was:<16>
[ERROR]   PutAuthWithNonAsciiCredentialsTest>PutTest.testArtifactUpload:68 expected:<8> but was:<16>
[INFO] 
[ERROR] Tests run: 93, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by mosabua** [comment]
Is this good to merge and release ?

**Comment by cstamas** [comment]
@mosabua This is just a test that will fail to prove the presence of the bug, this PR does not have fix in place for bug yet. If you merge this, you will effectively break the build 😄

**Comment by cstamas** [comment]
This repo is being archived

**Pull request closed without merging**
