### PR TITLE
Formally create an X509TrustManager

### PR DESCRIPTION
**Pull request by stewartfrancis**
Formally create an X509TrustManager rather than relying on OkHTTP's deprecated API which extracts one from the VM using reflection, which doesn't work with the IBM VM security provider.

### CODE REVIEW

**Comment by fbricon** [comment]
Takari requires signed [CLA](http://takari.io/support/TakariCLA.pdf) for all pull requests to be accepted.

**Comment by stewartfrancis** [comment]
@fbricon finally got this cleared with legal and have emailed to team@takari.io

**Comment by fbricon** [comment]
Ok thanks. I'll check everything once I get back to a computer.

**Comment by fbricon** [comment]
Fix works for IBM JDK and JDK 9. @jvanzyl can you merge it if you received the CLA?

**Pull request merged**
