### PR TITLE
RejectedExecutionException in m2e

### LINKED ISSUE #27: RejectedExecutionException in m2e
The issue has been introduced with https://github.com/takari/aether-connector-okhttp/commit/32ce3f86e2b6bc292b9f07d8306bc01a0c973605
It can be reproduced by importing spring-petclinic into an empty maven workspace.
See https://github.com/eclipse/eclipse.jdt.ls/pull/1369 and https://ci.eclipse.org/ls/job/jdt-ls-pr/1903/

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #27 

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### CODE REVIEW

**Comment by Eskibear** [comment]
LGTM. 
I'm shamed about the miss. 🤦‍♂

**Comment by jvanzyl** [comment]
You need another release?

**Comment by fbricon** [comment]
@Eskibear can you confirm this patch properly fixes the issue? If yes then @jvanzyl can proceed with the release we need

**Comment by Eskibear** [comment]
@fbricon The problem is, I cannot reproduce the error in [jdt-ls-pr/1903](https://ci.eclipse.org/ls/job/jdt-ls-pr/1903) locally. I tried running jdtls's test cases by replacing the `aether-connector-okhttp.jar` with the private built ones (the buggy one https://github.com/takari/aether-connector-okhttp/commit/32ce3f86e2b6bc292b9f07d8306bc01a0c973605, and the fixed one https://github.com/takari/aether-connector-okhttp/commit/612c2c3786d79869424e7b45be2ec66bac8f0fd1), and **both** were passed. 

What I can tell is: 
1. The error message was exactly about submitting a task to a closed threadpool.
2. In test cases of this repo, by manually closing the threadpool before submiting a job to download multiple artifacts, I got the same error. And this PR fixed the error. 

I'm not familiar with m2e, and I've no idea which component calls `connector.close()` and finally leads to the failed case. 
But for the question that if this patch properly fixes the issue, I'm sure that yes, it fixed the RejectedExecutionException issue.

**Comment by fbricon** [comment]
Ok then, @jvanzyl can you please proceed with the release of 0.17.8( make sure the version is updated)

**Comment by fbricon** [comment]
ping @jvanzyl

**Comment by mosabua** [comment]
hey all.. new release is cut and on the way to central .. should be there shortly

**Comment by mosabua** [comment]
https://repo1.maven.org/maven2/io/takari/aether/aether-connector-okhttp/0.17.8/

**Comment by fbricon** [comment]
@mosabua Thanks!

**Pull request merged**
