### PR TITLE
Use okhttp 3.14.1

### PR DESCRIPTION
**Pull request by tony--**
* use okio 1.17.3 to match okhttp 3.14.1
* use bouncycastle 1.60 to match okhttp 3.14.1

### CODE REVIEW

**Comment by tony--** [comment]
Two tests are failing after this change:
```
[ERROR] Tests run: 94, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 41.714 s <<< FAILURE! - in io.takari.aether.okhttp.OkHttpAetherTest
[ERROR] testAetherClientSSLProxyAuthHeaders(io.takari.aether.connector.test.mockwebserver.AetherMockWebserverConnectorTest)  Time elapsed: 0.011 s  <<< ERROR!
java.io.IOException: Failed to authenticate with proxy
	at io.takari.aether.connector.test.mockwebserver.AetherMockWebserverConnectorTest.testAetherClientSSLProxyAuthHeaders(AetherMockWebserverConnectorTest.java:525)

[ERROR] testProxyAuthenticateOnConnectOverSSL(io.takari.aether.connector.test.mockwebserver.AetherMockWebserverConnectorTest)  Time elapsed: 0.008 s  <<< ERROR!
java.io.IOException: Failed to authenticate with proxy
	at io.takari.aether.connector.test.mockwebserver.AetherMockWebserverConnectorTest.testProxyAuthenticateOnConnectOverSSL(AetherMockWebserverConnectorTest.java:435)
```

I imported the project into Eclipse to try to troubleshoot these, but errors occurred when trying to install takari-lifecycle-plugins.
Screenshot from 2019-04-23 15-26-21
It seems that https://download.takari.io/eclipse/takari-lifecycle/content.xml is not available so the plugins cannot be installed.
If someone can help me to resolve this issue, I will investigate the test failures and update the PR.

**Comment by fbricon** [comment]
Try installing the takari connector from this p2 repo: https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-takari-lifecycle/0.1.0/N/LATEST/

**Comment by tony--** [comment]
Thanks @fbricon.  Is this what you had in mind?
Screenshot from 2019-04-23 15-45-55
It seems to still go to download.takari.io and fail.

**Comment by fbricon** [comment]
Uncheck "contact all update sites" or disable the takari update site in the preferences (via the manage... button)

**Comment by tony--** [comment]
I disabled the takari update site.  Now I get:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Takari Build Lifecycle support 0.1.0.201812042350 (io.takari.m2e.lifecycle.feature.feature.group 0.1.0.201812042350)
  Missing requirement: Takari Build Lifecycle support 0.1.0.201812042350 (io.takari.m2e.lifecycle.feature.feature.group 0.1.0.201812042350) requires 'org.eclipse.equinox.p2.iu; io.takari.stats.m2e.feature.feature.group 0.1.0' but it could not be found
```

**Comment by fbricon** [comment]
meeeh ... add https://repo1.maven.org/maven2/.m2e/connectors/takari-team/0.1.0/N/LATEST/ to the list of available update sites and check "contact all update sites"

**Comment by fbricon** [comment]
sorry that'd be https://repo1.maven.org/maven2/.m2e/connectors/takari-stats-m2e/0.1.0/N/LATEST/

**Comment by tony--** [comment]
The first one worked too 😜 
Now it shows all items installed, but I am still getting "plugin execution not covered by lifecycle..." errors.
Screen Shot 2019-04-23 at 4 08 19 PM

**Comment by fbricon** [comment]
have you tried to right-click on the project and do  `Maven` > `Update project...`?

**Comment by tony--** [comment]
I had not, but after I tried it, it worked.  Thanks for the help @fbricon!

**Comment by tony--** [comment]
Both test failures are caused by IllegalStateExceptions:
```
SEVERE: MockWebServer[53377] connection from /127.0.0.1 crashed
java.lang.IllegalStateException: Tunnel without any CONNECT!
	at okhttp3.mockwebserver.MockWebServer$4.createTunnel(MockWebServer.java:554)
	at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:472)
	at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:456)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Because this started happening after upgrading the deps only, it makes me think that either the test must be changed for compatibility with the upgraded deps or (less likely) the test is detecting a real problem that has been surfaced due to changes in okhttp.

I'm still looking at this, but I'm a bit stuck and any help would be welcome.

**Comment by tony--** [comment]
The second commit makes tests pass by handling a feature added in okhttp 3.12.0.  See this PR for the change: https://github.com/square/okhttp/pull/4376

**Comment by gabe-brussa** [comment]
Hi @fbricon , is there something we can do to ease the review of this PR?
Ping @ifedorenko too :-)

**Comment by mosabua** [comment]
imho we should be good to merge. Not sure who manages releases at this stage

**Comment by tony--** [comment]
@fbricon @mosabua any suggestions for how to move this forward?

**Comment by fbricon** [comment]
So I kinda hit a wall at that point, I was setting up a new CI job on the Red Hat infra when I realized I don't need to expose a p2 repository but have to publish to Maven Central instead. That gets tricky. I have no control over publishing Takari artifacts over to Maven central and will need some help from @ifedorenko / @jvanzyl / @mosabua to move forward.

**Comment by mosabua** [comment]
I can cut a new release if you want..

**Comment by fbricon** [comment]
@mosabua thanks. I believe you need to bump the version, before merging the PR and releasing

**Comment by tony--** [comment]
Thanks @fbricon and @mosabua!

**Pull request merged**
