### PR TITLE
bugfix https and proxy authentication

### PR DESCRIPTION
**Pull request by slatequarry**

### CODE REVIEW

**Comment by jvanzyl** [comment]
Needs a test, preferably one that shows the issue that your patch fixes. Also you need to match the formatting.

**Comment by atanasenko** [comment]
This is actually the thing that generates some amount of emails on m2e lists about proxy authentication failures. Here's a corresponding bugzilla [1].
I've checked several versions of okhttp (2.3.0, 2.5.0, 2.7.2 and even latest 3.0.1) and they all just throw an IOException with this message when creating an ssl tunnel to https proxy which returns status 407.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=477893

**Comment by atanasenko** [comment]
Another fix possibility is adding Proxy-Authentication preemptively.

**Comment by jvanzyl** [comment]
Fix by @atanasenko with 5b500c664e757a940504e7fbb99f9f8edec81db0

**Pull request closed without merging**
