### PR TITLE
Updates to how Wagon handles status codes on transfers.

### PR DESCRIPTION
**Pull request by andham**
Signed-off-by: Anders Hammar <anders@hammar.net>

### CODE REVIEW

**Comment by ifedorenko** [comment]
What is the user-visible problem you are trying to solve?

**Comment by andham** [comment]
I'm trying to get this wagon to work with Maven 3.0.4. When deploying an artifact for the first time and the maven-metadata.xml file doesn't exist it fails as 404 is returned but ResourceDoesNotExistException is not thrown. Maven 3.0.4 doesn't cope with that. However, IIRC, Maven 3.2.x+ does handle it. In any case, the API indicates that exceptions should be thrown in specific cases and I therefore think that this wagon should do so.
(I fully appreciate that Maven 3.0.x is not intended to be supported, but I argue that this fix is to comply with the wagon API.)

There is actually a TCK for Apache wagon that probably should be run on this wagon: https://github.com/apache/maven-wagon/tree/master/wagon-tcks/wagon-tck-http
There is a test for 404 error there that expects ResourceDoesNotExistException.

**Comment by ifedorenko** [comment]
Makes sense. Thank you for the explanation.

**Comment by fbricon** [comment]
Applied to master. Thanks @andham !

**Pull request closed without merging**
